### ISSUE TITLE
Possible error in VCF reader (dev branch)

### ISSUE THREAD

**Issue by the-utkarshjain** [ML4GLand/SeqData#3]
Shouldn't there be an else statement at line 130 in seqdata/_io/readers/vcf.py (dev branch)?

![Screenshot 2023-07-24 at 11 00 27 AM](https://github.com/ML4GLand/SeqData/assets/45516528/cde6dd6e-d04e-498e-8088-600c9aba0e6f)

**Comment by d-laub** [comment]
Thanks for the catch! Fixed in b4ea3f6.
